import turtle
#turtle.speed(0)
#head
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.begin_fill()
turtle.color("black")
turtle.circle(200)
turtle.end_fill()
#left eye
turtle.penup()
turtle.goto(-70,40)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.circle(20)
turtle.end_fill()
#right eye
turtle.penup()
turtle.goto(70,40)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.circle(20)
turtle.end_fill()
#nose
turtle.penup()
turtle.goto(0,50)
turtle.pendown()
turtle.begin_fill()
turtle.right(180)
turtle.color("green")
turtle.circle(50, steps = 3)
turtle.end_fill()
#mouse
turtle.pensize(3)
turtle.color("red")
turtle.penup()
turtle.goto(0,-150)
turtle.pendown()
turtle.right(25)
turtle.forward(85)
turtle.penup()
turtle.goto(0,-150)
turtle.pendown()
turtle.right(130)
turtle.forward(85)

turtle.done()
