import turtle

turtle.penup()
turtle.goto(-200,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.left(60)
turtle.circle(40, steps = 3)
turtle.end_fill()
turtle.right(60)

turtle.penup()
turtle.goto(-100,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.left(45)
turtle.circle(40, steps = 4)
turtle.end_fill()
turtle.right(45)

turtle.penup()
turtle.goto(0,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("green")
turtle.left(36)
turtle.circle(40, steps = 5)
turtle.end_fill()
turtle.right(36)

turtle.penup()
turtle.goto(100,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("yellow")
turtle.left(30)
turtle.circle(40, steps = 6)
turtle.end_fill()
turtle.right(30)

turtle.penup()
turtle.goto(200,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("purple")
turtle.left(22.5)
turtle.circle(40, steps = 8)
turtle.end_fill()
turtle.right(22.5)

turtle.penup()
turtle.goto(-150,50)
turtle.pendown()
turtle.write("Cool Colorful Shapes", font = ("Time", 18, "bold"))
turtle.hideturtle()

turtle.done()
