import turtle

turtle.circle(20)
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.goto(0,-30)
turtle.pendown()
turtle.right(20)
turtle.forward(50)
turtle.penup()
turtle.goto(0,-30)
turtle.pendown()
turtle.left(40)
turtle.forward(50)
turtle.penup()
turtle.goto(0,-100)
turtle.pendown()
turtle.right(40)
turtle.forward(80)
turtle.penup()
turtle.goto(0,-100)
turtle.pendown()
turtle.left(40)
turtle.forward(80)

turtle.done()
